name: '🆘 Support request'
description: If you need help to use this library
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        ## Let's try to solve your problem

        **Please use English or French**, I don't speak other languages.

        Consider searching [the documentation](https://photo-sphere-viewer.js.org/guide/) to find the solution by yourself.

        Use [markdown codeblocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) when posting code samples.

  - type: textarea
    attributes:
      label: Describe your problem
      placeholder: A clear description of what you want to achieve and what you already tried. If possible provided an online demo of your progression.
    validations:
      required: true

  - type: input
    attributes:
      label: Online demo URL

  - type: input
    attributes:
      label: Photo Sphere Viewer version
    validations:
      required: true

  - type: input
    attributes:
      label: Plugins loaded

  - type: textarea
    attributes:
      label: Additional context
      placeholder: Add any other context about the feature request here.
