name: release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: github.repository == 'mistic100/Photo-Sphere-Viewer'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: data
        id: data
        run: |
          echo "PREVIOUS_TAG=$(git tag --sort=-committerdate | sed -n '2 p')" >> $GITHUB_OUTPUT
          echo "NPM_TAG=$(echo ${{ github.ref_name }} | cut -d '-' -f2 -s | cut -d '.' -f1 -s)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn ci:version ${{ github.ref_name }}
          yarn ci:build

      - name: package
        run: |
          echo '📂 prepare'
          node ./build/prepare-package.mjs
          echo '📦 archive'
          (cd dist && zip -r photo-sphere-viewer-${{ github.ref_name }}.zip .)
          echo '📄 changelog'
          git log --pretty=format:"%s" ${{ steps.data.outputs.PREVIOUS_TAG }}...${{ github.ref_name }} | node ./build/prepare-changelog.mjs ${{ steps.data.outputs.PREVIOUS_TAG }} ${{ github.ref_name }}

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_file: dist/changelog_${{ github.ref_name }}.md
          files: dist/photo-sphere-viewer-${{ github.ref_name }}.zip

      - name: npm publish
        run: |
          yarn ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_TAG: ${{ steps.data.outputs.NPM_TAG || 'latest' }}

      - uses: Akkjon/close-milestone@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          milestone_name: ${{ github.ref_name }}
          crash_on_missing: false

      - name: update issue templates
        run: |
          git fetch origin main --depth 1
          git checkout main
          node ./build/update-issue-templates.mjs ${{ github.ref_name }}
          git stage .github/ISSUE_TEMPLATE
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions"
          git commit -m "chore: add ${{ github.ref_name }} to issue templates"
          git push
