name: release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: github.repository == 'mistic100/Photo-Sphere-Viewer'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn ci:version ${{ github.ref_name }}
          yarn ci:build

      - name: package
        run: |
          echo '📂 prepare'
          node ./build/prepare-package.mjs
          echo '📦 archive'
          (cd dist && zip -r photo-sphere-viewer-${{ github.ref_name }}.zip .)

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/photo-sphere-viewer-${{ github.ref_name }}.zip

      - name: npm tag
        id: npm_tag
        run: |
          echo "NPM_TAG=$(echo ${{ github.ref_name }} | cut -d '-' -f2 -s | cut -d '.' -f1 -s)" >> $GITHUB_OUTPUT

      - name: npm publish
        run: |
          yarn ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_TAG: ${{ steps.npm_tag.outputs.NPM_TAG || 'latest' }}
